# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175bd8337cad76593833bf15c646f505100dbb9c32e13e44b343558b8192f9085598f6311f22009a905e4eb88094004bd3508797802ede14ab41457e6890eac0

test:
  secret_key_base: 4aae12abef8d3c2ad4df876a92fac9c32d9893c120b2f30acadefe9368999b1ad5b3e57cb9213459bca53099b8a0f9ffbb0ca900919a0707eac445d23d45c3cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>